/* AVIS DO NOT REMOVE
::AVIS FILEINFO V01.00::
FILE.NAME      = AdvancedSearchDialog.h;
FILE.TYPE      = HEADER;
FILE.VERSION   = V02.00;
FILE.MODULE    = CYBORG.MIGRATION.ADVANCED.SEARCH;
FILE.PATH      = <PROJECT>/include/AdvancedSearchDialog.h;
FILE.OWNER     = AI.FVS.AVIS.SYSTEM;

AVIS ADVANCED SEARCH DIALOG INTERFACE.
AVIS DO NOT REMOVE */

#ifndef CYBORG_ADVANCED_SEARCH_DIALOG_H
#define CYBORG_ADVANCED_SEARCH_DIALOG_H
#include "include/shared_inc.h"


BOOL AdvancedSearch_Show(HWND hParent, ADV_SEARCH_PARAMS *params);

#endif /* CYBORG_ADVANCED_SEARCH_DIALOG_H */
